// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: async.proto

package com.hello.haneda.api;

public final class Async {
  private Async() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface AckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Ack)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated uint64 message_id = 1;</code>
     */
    java.util.List<java.lang.Long> getMessageIdList();
    /**
     * <code>repeated uint64 message_id = 1;</code>
     */
    int getMessageIdCount();
    /**
     * <code>repeated uint64 message_id = 1;</code>
     */
    long getMessageId(int index);
  }
  /**
   * Protobuf type {@code Ack}
   */
  public static final class Ack extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:Ack)
      AckOrBuilder {
    // Use Ack.newBuilder() to construct.
    private Ack(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Ack(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Ack defaultInstance;
    public static Ack getDefaultInstance() {
      return defaultInstance;
    }

    public Ack getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Ack(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                messageId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              messageId_.add(input.readUInt64());
              break;
            }
            case 10: {
              int length = input.readRawVarint32();
              int limit = input.pushLimit(length);
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001) && input.getBytesUntilLimit() > 0) {
                messageId_ = new java.util.ArrayList<java.lang.Long>();
                mutable_bitField0_ |= 0x00000001;
              }
              while (input.getBytesUntilLimit() > 0) {
                messageId_.add(input.readUInt64());
              }
              input.popLimit(limit);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          messageId_ = java.util.Collections.unmodifiableList(messageId_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hello.haneda.api.Async.internal_static_Ack_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hello.haneda.api.Async.internal_static_Ack_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hello.haneda.api.Async.Ack.class, com.hello.haneda.api.Async.Ack.Builder.class);
    }

    public static com.google.protobuf.Parser<Ack> PARSER =
        new com.google.protobuf.AbstractParser<Ack>() {
      public Ack parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Ack(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Ack> getParserForType() {
      return PARSER;
    }

    public static final int MESSAGE_ID_FIELD_NUMBER = 1;
    private java.util.List<java.lang.Long> messageId_;
    /**
     * <code>repeated uint64 message_id = 1;</code>
     */
    public java.util.List<java.lang.Long>
        getMessageIdList() {
      return messageId_;
    }
    /**
     * <code>repeated uint64 message_id = 1;</code>
     */
    public int getMessageIdCount() {
      return messageId_.size();
    }
    /**
     * <code>repeated uint64 message_id = 1;</code>
     */
    public long getMessageId(int index) {
      return messageId_.get(index);
    }

    private void initFields() {
      messageId_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < messageId_.size(); i++) {
        output.writeUInt64(1, messageId_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < messageId_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeUInt64SizeNoTag(messageId_.get(i));
        }
        size += dataSize;
        size += 1 * getMessageIdList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hello.haneda.api.Async.Ack parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.haneda.api.Async.Ack parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.haneda.api.Async.Ack parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hello.haneda.api.Async.Ack parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hello.haneda.api.Async.Ack parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.haneda.api.Async.Ack parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hello.haneda.api.Async.Ack parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hello.haneda.api.Async.Ack parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hello.haneda.api.Async.Ack parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hello.haneda.api.Async.Ack parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hello.haneda.api.Async.Ack prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Ack}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Ack)
        com.hello.haneda.api.Async.AckOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hello.haneda.api.Async.internal_static_Ack_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hello.haneda.api.Async.internal_static_Ack_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hello.haneda.api.Async.Ack.class, com.hello.haneda.api.Async.Ack.Builder.class);
      }

      // Construct using com.hello.haneda.api.Async.Ack.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        messageId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hello.haneda.api.Async.internal_static_Ack_descriptor;
      }

      public com.hello.haneda.api.Async.Ack getDefaultInstanceForType() {
        return com.hello.haneda.api.Async.Ack.getDefaultInstance();
      }

      public com.hello.haneda.api.Async.Ack build() {
        com.hello.haneda.api.Async.Ack result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hello.haneda.api.Async.Ack buildPartial() {
        com.hello.haneda.api.Async.Ack result = new com.hello.haneda.api.Async.Ack(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          messageId_ = java.util.Collections.unmodifiableList(messageId_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.messageId_ = messageId_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hello.haneda.api.Async.Ack) {
          return mergeFrom((com.hello.haneda.api.Async.Ack)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hello.haneda.api.Async.Ack other) {
        if (other == com.hello.haneda.api.Async.Ack.getDefaultInstance()) return this;
        if (!other.messageId_.isEmpty()) {
          if (messageId_.isEmpty()) {
            messageId_ = other.messageId_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureMessageIdIsMutable();
            messageId_.addAll(other.messageId_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hello.haneda.api.Async.Ack parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hello.haneda.api.Async.Ack) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<java.lang.Long> messageId_ = java.util.Collections.emptyList();
      private void ensureMessageIdIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          messageId_ = new java.util.ArrayList<java.lang.Long>(messageId_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated uint64 message_id = 1;</code>
       */
      public java.util.List<java.lang.Long>
          getMessageIdList() {
        return java.util.Collections.unmodifiableList(messageId_);
      }
      /**
       * <code>repeated uint64 message_id = 1;</code>
       */
      public int getMessageIdCount() {
        return messageId_.size();
      }
      /**
       * <code>repeated uint64 message_id = 1;</code>
       */
      public long getMessageId(int index) {
        return messageId_.get(index);
      }
      /**
       * <code>repeated uint64 message_id = 1;</code>
       */
      public Builder setMessageId(
          int index, long value) {
        ensureMessageIdIsMutable();
        messageId_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 message_id = 1;</code>
       */
      public Builder addMessageId(long value) {
        ensureMessageIdIsMutable();
        messageId_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 message_id = 1;</code>
       */
      public Builder addAllMessageId(
          java.lang.Iterable<? extends java.lang.Long> values) {
        ensureMessageIdIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, messageId_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated uint64 message_id = 1;</code>
       */
      public Builder clearMessageId() {
        messageId_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Ack)
    }

    static {
      defaultInstance = new Ack(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Ack)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Ack_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Ack_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013async.proto\"\031\n\003Ack\022\022\n\nmessage_id\030\001 \003(\004" +
      "B\026\n\024com.hello.haneda.api"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Ack_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Ack_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_Ack_descriptor,
        new java.lang.String[] { "MessageId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
